# Generates version.inc.h — the build metadata consumed by
# lib/corelibs/lib/version/version.c. Runs in CMake script mode (-P) from the
# version_inc target, i.e. on every build rather than once at configure time, so
# the commit, branch and dirty flag always describe the tree actually being
# compiled. The header is only rewritten when its content changes, so version.c
# is not recompiled by a build that did not change anything git-visible.
#
# Inputs (all -D):
#   SOURCE_DIR       repository root, the git working tree to describe
#   OUTPUT           path of the header to produce
#   FIRMWARE_TARGET  numeric hardware target (f1 -> 1)
#   FIRMWARE_ORIGIN  "Official" or a fork name
#
# CI overrides, read from the environment (set by scripts/get_env.py):
#   COMMIT_SHA, BRANCH_NAME, DIST_SUFFIX

foreach(_var SOURCE_DIR OUTPUT FIRMWARE_TARGET FIRMWARE_ORIGIN)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "version_inc.cmake: -D${_var} is required")
    endif()
endforeach()

# Runs a git command in SOURCE_DIR; leaves ${_out} empty on any failure.
function(_git _out)
    execute_process(
        COMMAND git -C "${SOURCE_DIR}" ${ARGN}
        OUTPUT_VARIABLE _result
        RESULT_VARIABLE _status
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(NOT _status EQUAL 0)
        set(_result "")
    endif()
    set(${_out} "${_result}" PARENT_SCOPE)
endfunction()

# Environment override wins when set and non-empty, then git, then a fallback.
function(_pick _out _env _git_value _fallback)
    if(DEFINED ENV{${_env}} AND NOT "$ENV{${_env}}" STREQUAL "")
        set(${_out} "$ENV{${_env}}" PARENT_SCOPE)
    elseif(NOT "${_git_value}" STREQUAL "")
        set(${_out} "${_git_value}" PARENT_SCOPE)
    else()
        set(${_out} "${_fallback}" PARENT_SCOPE)
    endif()
endfunction()

_git(_commit rev-parse --short HEAD)
_pick(GIT_COMMIT COMMIT_SHA "${_commit}" "unknown")

_git(_branch rev-parse --abbrev-ref HEAD)
_pick(GIT_BRANCH BRANCH_NAME "${_branch}" "unknown")

# Last tag if there is one, otherwise r<commit count>
_git(_version describe --tags --abbrev=0)
if(NOT _version)
    _git(_count rev-list --count HEAD)
    if(_count)
        set(_version "r${_count}")
    endif()
endif()
_pick(VERSION DIST_SUFFIX "${_version}" "unknown")

_git(_status status --porcelain)
if(_status)
    set(BUILD_DIRTY 1)
else()
    set(BUILD_DIRTY 0)
endif()

_git(_origin remote get-url origin)
_pick(GIT_ORIGIN _UNUSED_ "${_origin}" "unknown")

string(TIMESTAMP BUILD_DATE "%Y-%m-%d")

# Values end up inside C string literals
foreach(_var GIT_COMMIT GIT_BRANCH VERSION GIT_ORIGIN FIRMWARE_ORIGIN)
    string(REPLACE "\\" "\\\\" ${_var} "${${_var}}")
    string(REPLACE "\"" "\\\"" ${_var} "${${_var}}")
endforeach()

set(_content "\
/* Generated by scripts/cmake/version_inc.cmake at build time — do not edit. */
#pragma once

#define GIT_COMMIT      \"${GIT_COMMIT}\"
#define GIT_BRANCH      \"${GIT_BRANCH}\"
#define VERSION         \"${VERSION}\"
#define BUILD_DIRTY     ${BUILD_DIRTY}
#define GIT_ORIGIN      \"${GIT_ORIGIN}\"
#define BUILD_DATE      \"${BUILD_DATE}\"
#define TARGET          ${FIRMWARE_TARGET}
#define FIRMWARE_ORIGIN \"${FIRMWARE_ORIGIN}\"
")

# Write to a temporary and copy over only on change, so the header's mtime — and
# with it the recompilation of version.c — moves only when the content does.
get_filename_component(_out_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")
file(WRITE "${OUTPUT}.tmp" "${_content}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}"
    RESULT_VARIABLE _copy_status)
file(REMOVE "${OUTPUT}.tmp")
if(NOT _copy_status EQUAL 0)
    message(FATAL_ERROR "version_inc.cmake: failed to write ${OUTPUT}")
endif()
