#pragma once

#define FURI_POWER_CONFIG_INA_SHUNT_RESISTOR_OHMS (0.01f)
#define FURI_POWER_CONFIG_INA_BUS_CURRENT_MAX     (9.0f)

#define FURI_POWER_CONFIG_BQ2579X_BAT_MAX_CHARGE_VOLTAGE 8650
#define FURI_POWER_CONFIG_BQ2579X_BAT_MAX_CHARGE_CURRENT 3000
#define FURI_POWER_CONFIG_BQ2579X_BAT_MAX_INPUT_CURRENT  3000