#include "cli_vcp.h"
#include <furi_hal.h>
#include <furi.h>
#include <api_lock.h>
#include <cli/shell/cli_shell.h>
#include <cli/cli_main_shell.h>
#include <cli/cli_commands.h>
#include <tusb.h>
#include <furi_hal_usb_cdc.h>

#define TAG "CliVcp"

#define USB_CDC_PKT_LEN      (CFG_TUD_CDC_RX_BUFSIZE - 1) //Todo: 2 txdone, when sending a full 64-byte packet
#define VCP_BUF_SIZE         (USB_CDC_PKT_LEN * 16)
#define VCP_IF_NUM           0
#define VCP_MESSAGE_Q_LEN    5
#define CLI_VCP_SHELL_PROMPT "control"

//#define CLI_VCP_DEBUG_ENABLE

#ifdef CLI_VCP_DEBUG_ENABLE
#define CLI_VCP_DEBUG(...) FURI_LOG_D(__VA_ARGS__)
#else
#define CLI_VCP_DEBUG(...)
#endif

typedef struct {
    enum {
        CliVcpMessageTypeEnable,
        CliVcpMessageTypeDisable,
    } type;
    FuriApiLock api_lock;
    union {};
} CliVcpMessage;

typedef enum {
    CliVcpEventConnected = (1 << 0),
    CliVcpEventDisconnected = (1 << 1),
    CliVcpEventTxDone = (1 << 2),
    CliVcpEventTx = (1 << 3),
    CliVcpEventRx = (1 << 4),
    CliVcpEventAll = (CliVcpEventConnected | CliVcpEventDisconnected | CliVcpEventTxDone | CliVcpEventTx | CliVcpEventRx),
} CliVcpEvent;

struct CliVcp {
    FuriEventLoop* event_loop;
    FuriMessageQueue* message_queue; // <! external messages
    FuriEventFlag* event_flag;

    bool is_enabled, is_connected;

    PipeSide* own_pipe;
    PipeSide* shell_pipe;
    volatile bool is_currently_transmitting;

    CliRegistry* main_registry;
    CliShell* shell;
};

// ============
// Data copying
// ============

/**
 * Called in the following cases:
 *   - previous transfer has finished;
 *   - new data became available to send.
 */
static void cli_vcp_maybe_send_data(CliVcp* cli_vcp) {
    if(!cli_vcp->own_pipe) return;

    size_t length = pipe_bytes_available(cli_vcp->own_pipe);
    if(length > 0) {
        cli_vcp->is_currently_transmitting = true;
        uint8_t buf[USB_CDC_PKT_LEN];
        size_t to_receive_from_pipe = MIN(sizeof(buf), pipe_bytes_available(cli_vcp->own_pipe));
        length = pipe_receive(cli_vcp->own_pipe, buf, to_receive_from_pipe);
        furi_check(length == to_receive_from_pipe);
        CLI_VCP_DEBUG(TAG, "cdc_send length=%zu", length);
        furi_hal_cdc_send(VCP_IF_NUM, buf, length);
    } else {
        cli_vcp->is_currently_transmitting = false;
    }
}

/**
 * Called in the following cases:
 *   - new data arrived at the endpoint;
 *   - data was read out of the pipe.
 */
static void cli_vcp_maybe_receive_data(CliVcp* cli_vcp) {
    if(!cli_vcp->own_pipe) return;
    if(pipe_spaces_available(cli_vcp->own_pipe) < USB_CDC_PKT_LEN) return;

    uint8_t buf[USB_CDC_PKT_LEN];
    int32_t length = furi_hal_cdc_receive(VCP_IF_NUM, buf, sizeof(buf));
    if(length > 0) {
        CLI_VCP_DEBUG(TAG, "cdc_receive length=%ld", length);
        furi_check(pipe_send(cli_vcp->own_pipe, buf, length) == length);
    }
}

// =============
// CDC callbacks
// =============

static void cli_vcp_signal_event(CliVcp* cli_vcp, CliVcpEvent event) {
    uint32_t ret = furi_event_flag_set(cli_vcp->event_flag, event);
    if((ret & FuriFlagError)) {
        FURI_LOG_E(TAG, "Failed to set event flag, error code: 0x%08lX", ret);
    }
}

static void cli_vcp_cdc_tx_done(void* context) {
    CliVcp* cli_vcp = context;
    cli_vcp_signal_event(cli_vcp, CliVcpEventTxDone);
}

static void cli_vcp_cdc_rx(void* context) {
    CliVcp* cli_vcp = context;
    cli_vcp_signal_event(cli_vcp, CliVcpEventRx);
}

static void cli_vcp_cdc_state_callback(void* context, uint8_t state) {
    CliVcp* cli_vcp = context;
    if(state == 0) {
        cli_vcp_signal_event(cli_vcp, CliVcpEventDisconnected);
    }
    // `Connected` events are generated by DTR going active
}

static void cli_vcp_cdc_ctrl_line_callback(void* context, uint8_t ctrl_lines) {
    CliVcp* cli_vcp = context;
    bool dtr = ctrl_lines & (1 << 0);

    if(dtr == true) {
        cli_vcp_signal_event(cli_vcp, CliVcpEventConnected);
    } else {
        cli_vcp_signal_event(cli_vcp, CliVcpEventDisconnected);
    }
}

static CdcCallbacks cdc_cb = {
    cli_vcp_cdc_tx_done,
    cli_vcp_cdc_rx,
    cli_vcp_cdc_state_callback,
    cli_vcp_cdc_ctrl_line_callback,
    NULL,
};

// ======================
// Pipe callback handlers
// ======================

static void cli_vcp_data_from_shell(PipeSide* pipe, void* context) {
    UNUSED(pipe);
    CliVcp* cli_vcp = context;
    CLI_VCP_DEBUG(TAG, "data_from_shell");
    if(!cli_vcp->is_currently_transmitting) {
        cli_vcp_signal_event(cli_vcp, CliVcpEventTx);
    }
}

static void cli_vcp_shell_ready(PipeSide* pipe, void* context) {
    UNUSED(pipe);
    CliVcp* cli_vcp = context;
    CLI_VCP_DEBUG(TAG, "shell_ready");
    cli_vcp_maybe_receive_data(cli_vcp);
}

/**
 * Processes messages arriving from other threads
 */
static void cli_vcp_message_received(FuriEventLoopObject* object, void* context) {
    CliVcp* cli_vcp = context;
    CliVcpMessage message;
    furi_check(furi_message_queue_get(object, &message, 0) == FuriStatusOk);

    switch(message.type) {
    case CliVcpMessageTypeEnable:
        if(cli_vcp->is_enabled) break;
        FURI_LOG_D(TAG, "Enabling");
        cli_vcp->is_enabled = true;

        furi_hal_usb_cdc_init();
        furi_hal_cdc_set_callbacks(VCP_IF_NUM, &cdc_cb, cli_vcp);
        break;

    case CliVcpMessageTypeDisable:
        if(!cli_vcp->is_enabled) break;
        FURI_LOG_D(TAG, "Disabling");
        cli_vcp->is_enabled = false;

        furi_hal_cdc_set_callbacks(VCP_IF_NUM, NULL, NULL);
        furi_hal_usb_cdc_deinit();
        break;
    }

    api_lock_unlock(message.api_lock);
}

/**
 * Processes messages arriving from CDC event callbacks
 */
static void cli_vcp_event_happened(FuriEventLoopObject* object, void* context) {
    CliVcp* cli_vcp = context;

    uint32_t event = furi_event_flag_clear(object, CliVcpEventAll);

    if(event & FuriFlagError) {
        FURI_LOG_E(TAG, "Error while waiting for event flag, error code: 0x%08lX", event);
        return;
    }

    if(event & CliVcpEventRx) {
        CLI_VCP_DEBUG(TAG, "Rx");
        cli_vcp_maybe_receive_data(cli_vcp);
    }

    if(event & CliVcpEventTxDone) {
        CLI_VCP_DEBUG(TAG, "TxDone");
        event |= CliVcpEventTx; // trigger sending next packet if there is more data
    }

    if(event & CliVcpEventTx) {
        CLI_VCP_DEBUG(TAG, "Tx");
        cli_vcp_maybe_send_data(cli_vcp);
    }

    if(event & CliVcpEventDisconnected) {
        if(cli_vcp->is_connected) {
            FURI_LOG_D(TAG, "Disconnected");
            cli_vcp->is_connected = false;

            // disconnect our side of the pipe
            pipe_detach_from_event_loop(cli_vcp->own_pipe);
            pipe_free(cli_vcp->own_pipe);
            cli_vcp->own_pipe = NULL;

            // wait for shell to stop
            cli_shell_join(cli_vcp->shell);
            cli_shell_free(cli_vcp->shell);

            furi_record_close(RECORD_CLI);
            cli_vcp->main_registry = NULL;

            pipe_free(cli_vcp->shell_pipe);
        }
    }

    if(event & CliVcpEventConnected) {
        if(!cli_vcp->is_connected) {
            FURI_LOG_D(TAG, "Connected");
            cli_vcp->is_connected = true;
            cli_vcp->main_registry = furi_record_open(RECORD_CLI);
            // start shell thread
            PipeSideBundle bundle = pipe_alloc(VCP_BUF_SIZE, 1);
            cli_vcp->own_pipe = bundle.alices_side;
            cli_vcp->shell_pipe = bundle.bobs_side;
            pipe_attach_to_event_loop(cli_vcp->own_pipe, cli_vcp->event_loop);
            pipe_set_callback_context(cli_vcp->own_pipe, cli_vcp);
            pipe_set_data_arrived_callback(cli_vcp->own_pipe, cli_vcp_data_from_shell, FuriEventLoopEventFlagEdge);
            pipe_set_space_freed_callback(cli_vcp->own_pipe, cli_vcp_shell_ready, FuriEventLoopEventFlagEdge);
            furi_delay_ms(33); // we are too fast, minicom isn't ready yet
            cli_vcp->shell = cli_shell_alloc(cli_main_motd, NULL, cli_vcp->shell_pipe, cli_vcp->main_registry, NULL);
            cli_shell_set_prompt(cli_vcp->shell, CLI_VCP_SHELL_PROMPT);
            cli_shell_start(cli_vcp->shell);
        }
    }
}

// ============
// Thread stuff
// ============

static CliVcp* cli_vcp_alloc(void) {
    CliVcp* cli_vcp = malloc(sizeof(CliVcp));

    cli_vcp->event_loop = furi_event_loop_alloc();

    cli_vcp->message_queue = furi_message_queue_alloc(VCP_MESSAGE_Q_LEN, sizeof(CliVcpMessage));
    furi_event_loop_subscribe_message_queue(cli_vcp->event_loop, cli_vcp->message_queue, FuriEventLoopEventIn, cli_vcp_message_received, cli_vcp);

    cli_vcp->event_flag = furi_event_flag_alloc();
    furi_event_loop_subscribe_event_flag(
        cli_vcp->event_loop, cli_vcp->event_flag, FuriEventLoopEventIn | FuriEventLoopEventFlagEdge, cli_vcp_event_happened, cli_vcp);

    cli_vcp->is_enabled = false;
    cli_vcp->is_connected = false;
    cli_vcp->own_pipe = NULL;
    cli_vcp->shell_pipe = NULL;
    cli_vcp->is_currently_transmitting = false;

    return cli_vcp;
}

int32_t cli_vcp_srv(void* p) {
    UNUSED(p);

    CliVcp* cli_vcp = cli_vcp_alloc();
    furi_record_create(RECORD_CLI_VCP, cli_vcp);
    furi_event_loop_run(cli_vcp->event_loop);

    return 0;
}

// ==========
// Public API
// ==========

static void cli_vcp_synchronous_request(CliVcp* cli_vcp, CliVcpMessage* message) {
    message->api_lock = api_lock_alloc_locked();
    furi_message_queue_put(cli_vcp->message_queue, message, FuriWaitForever);
    api_lock_wait_unlock_and_free(message->api_lock);
}

void cli_vcp_enable(CliVcp* cli_vcp) {
    furi_check(cli_vcp);
    CliVcpMessage message = {
        .type = CliVcpMessageTypeEnable,
    };
    cli_vcp_synchronous_request(cli_vcp, &message);
}

void cli_vcp_disable(CliVcp* cli_vcp) {
    furi_check(cli_vcp);
    CliVcpMessage message = {
        .type = CliVcpMessageTypeDisable,
    };
    cli_vcp_synchronous_request(cli_vcp, &message);
}
