name: 'Build'

on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}"
        mkdir -p "${{ github.workspace }}"

    - name: Install dependencies
      run: |
        sudo apt-get install cmake
        wget https://github.com/xpack-dev-tools/gcc-xpack/releases/download/v14.3.0-1/xpack-gcc-14.3.0-1-linux-x64.tar.gz
        tar -xzf xpack-gcc-14.3.0-1-linux-x64.tar.gz
        export PATH=$PWD/xpack-gcc-14.3.0-1-linux-x64/bin:$PATH
        echo "$PWD/xpack-gcc-14.3.0-1-linux-x64/bin" >> $GITHUB_PATH

    - name: Checkout firmware
      uses: actions/checkout@v6
      with:
        path: firmware
        submodules: recursive

    - name: Checkout pico-sdk/2.2.0
      uses: actions/checkout@v6
      with:
        repository: raspberrypi/pico-sdk
        ref: 2.2.0
        path: pico-sdk

    - name: Checkout pico-sdk submodules
      working-directory: ${{github.workspace}}/pico-sdk
      run: git submodule update --init

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{github.workspace}}/firmware
      run:  cmake -E make_directory ${{github.workspace}}/firmware/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/firmware/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: PICO_SDK_PATH=../../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l

    - name: Build
      working-directory: ${{github.workspace}}/firmware/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE --parallel $(nproc)